apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-http-config
  namespace: homelab
data:
  http.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
        - 192.168.0.65/32
        - 0.0.0.0/0
