# ---
# # yaml-language-server: $schema=https://json.schemastore.org/kustomization
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: homelab
# resources:
#   - ./postgres.yaml
#   - ./backend.yaml
#   - ./frontend.yaml
#   - ./fivefilters.yaml
